// File generated by the BNF Converter (bnfc 2.9.5).

package forth_parser.Absyn;

public class Define  extends Expr {
  public final Word word_;
  public final Statement statement_;
  public Define(Word p1, Statement p2) { word_ = p1; statement_ = p2; }

  public <R,A> R accept(forth_parser.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof forth_parser.Absyn.Define) {
      forth_parser.Absyn.Define x = (forth_parser.Absyn.Define)o;
      return this.word_.equals(x.word_) && this.statement_.equals(x.statement_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.word_.hashCode())+this.statement_.hashCode();
  }


}
