// File generated by the BNF Converter (bnfc 2.9.5).

package forth_parser.Absyn;

public abstract class Expr implements java.io.Serializable {
  public abstract <R,A> R accept(Expr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(forth_parser.Absyn.Conditional p, A arg);
    public R visit(forth_parser.Absyn.Loop p, A arg);
    public R visit(forth_parser.Absyn.Define p, A arg);

  }

}
