// File generated by the BNF Converter (bnfc 2.9.5).

package forth_parser.Absyn;

public class Expression  extends Statement {
  public final Expr expr_;
  public Expression(Expr p1) { expr_ = p1; }

  public <R,A> R accept(forth_parser.Absyn.Statement.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof forth_parser.Absyn.Expression) {
      forth_parser.Absyn.Expression x = (forth_parser.Absyn.Expression)o;
      return this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return this.expr_.hashCode();
  }


}
