// File generated by the BNF Converter (bnfc 2.9.5).

package forth_parser.Absyn;

public class Literal  extends Statement {
  public final Constant constant_;
  public Literal(Constant p1) { constant_ = p1; }

  public <R,A> R accept(forth_parser.Absyn.Statement.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof forth_parser.Absyn.Literal) {
      forth_parser.Absyn.Literal x = (forth_parser.Absyn.Literal)o;
      return this.constant_.equals(x.constant_);
    }
    return false;
  }

  public int hashCode() {
    return this.constant_.hashCode();
  }


}
