// File generated by the BNF Converter (bnfc 2.9.5).

package forth_parser.Absyn;

public class Name  extends Word {
  public final String forthword_;
  public Name(String p1) { forthword_ = p1; }

  public <R,A> R accept(forth_parser.Absyn.Word.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof forth_parser.Absyn.Name) {
      forth_parser.Absyn.Name x = (forth_parser.Absyn.Name)o;
      return this.forthword_.equals(x.forthword_);
    }
    return false;
  }

  public int hashCode() {
    return this.forthword_.hashCode();
  }


}
