// File generated by the BNF Converter (bnfc 2.9.5).

package forth_parser.Absyn;

public class Number  extends Constant {
  public final Integer integer_;
  public Number(Integer p1) { integer_ = p1; }

  public <R,A> R accept(forth_parser.Absyn.Constant.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof forth_parser.Absyn.Number) {
      forth_parser.Absyn.Number x = (forth_parser.Absyn.Number)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
