// File generated by the BNF Converter (bnfc 2.9.5).

package forth_parser.Absyn;

public class Program  extends Prg {
  public final ListStatement liststatement_;
  public Program(ListStatement p1) { liststatement_ = p1; }

  public <R,A> R accept(forth_parser.Absyn.Prg.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof forth_parser.Absyn.Program) {
      forth_parser.Absyn.Program x = (forth_parser.Absyn.Program)o;
      return this.liststatement_.equals(x.liststatement_);
    }
    return false;
  }

  public int hashCode() {
    return this.liststatement_.hashCode();
  }


}
