// File generated by the BNF Converter (bnfc 2.9.5).

package forth_parser.Absyn;

public class SinlgeWord  extends Statement {
  public final Word word_;
  public SinlgeWord(Word p1) { word_ = p1; }

  public <R,A> R accept(forth_parser.Absyn.Statement.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof forth_parser.Absyn.SinlgeWord) {
      forth_parser.Absyn.SinlgeWord x = (forth_parser.Absyn.SinlgeWord)o;
      return this.word_.equals(x.word_);
    }
    return false;
  }

  public int hashCode() {
    return this.word_.hashCode();
  }


}
