// File generated by the BNF Converter (bnfc 2.9.5).

package forth_parser.Absyn;

public abstract class Statement implements java.io.Serializable {
  public abstract <R,A> R accept(Statement.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(forth_parser.Absyn.Literal p, A arg);
    public R visit(forth_parser.Absyn.Expression p, A arg);
    public R visit(forth_parser.Absyn.SinlgeWord p, A arg);

  }

}
