// File generated by the BNF Converter (bnfc 2.9.5).

package forth_parser.Absyn;

public abstract class Word implements java.io.Serializable {
  public abstract <R,A> R accept(Word.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(forth_parser.Absyn.Name p, A arg);

  }

}
