// File generated by the BNF Converter (bnfc 2.9.5).

package forth_parser;

/** All Visitor */

public interface AllVisitor<R,A> extends
  forth_parser.Absyn.Prg.Visitor<R,A>,
  forth_parser.Absyn.Statement.Visitor<R,A>,
  forth_parser.Absyn.Expr.Visitor<R,A>,
  forth_parser.Absyn.Word.Visitor<R,A>,
  forth_parser.Absyn.Constant.Visitor<R,A>
{}
