/* File generated by the BNF Converter (bnfc 2.9.5). */

#ifndef PARSER_HEADER_FILE
#define PARSER_HEADER_FILE

#include <stdio.h>
#include "Absyn.h"

Prg  pPrg(FILE *inp);
Prg psPrg(const char *str);

#endif
