/* File generated by the BNF Converter (bnfc 2.9.5). */

#ifndef PRINTER_HEADER
#define PRINTER_HEADER

#include "Absyn.h"

/* Certain applications may improve performance by changing the buffer size */
#define BUFFER_INITIAL 2048
/* You may wish to change _L_PAREN or _R_PAREN */
#define _L_PAREN '('
#define _R_PAREN ')'

/* The following are simple heuristics for rendering terminals */
/* You may wish to change them */
void renderCC(Char c);
void renderCS(String s);
void indent(void);
void backup(void);
void onEmptyLine(void);
void removeTrailingSpaces(void);
void removeTrailingWhitespace(void);


char *printPrg(Prg p);

void ppPrg(Prg p, int i);
void ppListStatement(ListStatement p, int i);
void ppStatement(Statement p, int i);
void ppExpr(Expr p, int i);
void ppWord(Word p, int i);
void ppConstant(Constant p, int i);
void ppListExpr(ListExpr p, int i);

char *showPrg(Prg p);

void shPrg(Prg p);
void shListStatement(ListStatement p);
void shStatement(Statement p);
void shExpr(Expr p);
void shWord(Word p);
void shConstant(Constant p);
void shListExpr(ListExpr p);

void ppForthWord(String s, int i);
void shForthWord(String s);
void ppInteger(Integer n, int i);
void ppDouble(Double d, int i);
void ppChar(Char c, int i);
void ppString(String s, int i);
void ppIdent(String s, int i);
void shInteger(Integer n);
void shDouble(Double d);
void shChar(Char c);
void shString(String s);
void shIdent(String s);
void bufEscapeS(const char *s);
void bufEscapeC(const char c);
void bufAppendS(const char *s);
void bufAppendC(const char c);
void bufReset(void);
void resizeBuffer(void);

#endif

