/* File generated by the BNF Converter (bnfc 2.9.5). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <ctype.h>   /* isspace */
#include <stddef.h>  /* size_t */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "Printer.h"

#define INDENT_WIDTH 2

int _n_;
char *buf_;
size_t cur_;
size_t buf_size;

/* You may wish to change the renderC functions */
void renderC(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppendC(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppendC('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppendC(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ' ') bufAppendC(c);
  else if (c == 0) return;
  else
  {
     bufAppendC(c);
     bufAppendC(' ');
  }
}

int allIsSpace(String s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return 0;
  return 1;
}

void renderS(String s)
{
  if (*s) /* s[0] != '\0', string s not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppendS(s);
    } else {
      bufAppendS(s);
      bufAppendC(' ');
    }
  }
}

void indent(void)
{
  int n = _n_;
  while (--n >= 0)
    bufAppendC(' ');
}

void backup(void)
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppendC('\n');
  indent();
}
char *printPrg(Prg p)
{
  _n_ = 0;
  bufReset();
  ppPrg(p, 0);
  return buf_;
}
char *showPrg(Prg p)
{
  _n_ = 0;
  bufReset();
  shPrg(p);
  return buf_;
}
void ppPrg(Prg p, int _i_)
{
  switch(p->kind)
  {
  case is_Program:
    if (_i_ > 0) renderC(_L_PAREN);
    ppListStatement(p->u.program_.liststatement_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Prg!\n");
    exit(1);
  }
}

void ppListStatement(ListStatement liststatement, int i)
{
  if (liststatement == 0)
  { /* nil */
  }
  else if (liststatement->liststatement_ == 0)
  { /* last */
    ppStatement(liststatement->statement_, 0);
  }
  else
  { /* cons */
    ppStatement(liststatement->statement_, 0);
    ppListStatement(liststatement->liststatement_, 0);
  }
}

void ppStatement(Statement p, int _i_)
{
  switch(p->kind)
  {
  case is_Literal:
    if (_i_ > 0) renderC(_L_PAREN);
    ppConstant(p->u.literal_.constant_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Expression:
    if (_i_ > 0) renderC(_L_PAREN);
    ppExpr(p->u.expression_.expr_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_SinlgeWord:
    if (_i_ > 0) renderC(_L_PAREN);
    ppWord(p->u.sinlgeword_.word_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Statement!\n");
    exit(1);
  }
}

void ppExpr(Expr p, int _i_)
{
  switch(p->kind)
  {
  case is_Conditional:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("if");
    ppStatement(p->u.conditional_.statement_, 0);
    renderS("then");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Loop:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("begin");
    ppStatement(p->u.loop_.statement_, 0);
    renderS("until");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Define:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC(':');
    ppWord(p->u.define_.word_, 0);
    ppStatement(p->u.define_.statement_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Expr!\n");
    exit(1);
  }
}

void ppWord(Word p, int _i_)
{
  switch(p->kind)
  {
  case is_Name:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.name_.forthword_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Word!\n");
    exit(1);
  }
}

void ppConstant(Constant p, int _i_)
{
  switch(p->kind)
  {
  case is_Number:
    if (_i_ > 0) renderC(_L_PAREN);
    ppInteger(p->u.number_.integer_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Constant!\n");
    exit(1);
  }
}

void ppListExpr(ListExpr listexpr, int i)
{
  if (listexpr == 0)
  { /* nil */
  }
  else if (listexpr->listexpr_ == 0)
  { /* last */
    ppExpr(listexpr->expr_, 0); renderC(' ');
  }
  else
  { /* cons */
    ppExpr(listexpr->expr_, 0);
    renderC(' ');
    ppListExpr(listexpr->listexpr_, 0);
  }
}

void ppInteger(Integer n, int i)
{
  char tmp[20];
  sprintf(tmp, "%d", n);
  renderS(tmp);
}
void ppDouble(Double d, int i)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  renderS(tmp);
}
void ppChar(Char c, int i)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
  bufAppendC(' ');
}
void ppString(String s, int i)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
  bufAppendC(' ');
}
void ppIdent(String s, int i)
{
  renderS(s);
}

void ppForthWord(String s, int i)
{
  renderS(s);
}


void shPrg(Prg p)
{
  switch(p->kind)
  {
  case is_Program:
    bufAppendC('(');

    bufAppendS("Program");

    bufAppendC(' ');

    shListStatement(p->u.program_.liststatement_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Prg!\n");
    exit(1);
  }
}

void shListStatement(ListStatement liststatement)
{
  bufAppendC('[');
  while(liststatement != 0)
  {
    if (liststatement->liststatement_)
    {
      shStatement(liststatement->statement_);
      bufAppendS(", ");
      liststatement = liststatement->liststatement_;
    }
    else
    {
      shStatement(liststatement->statement_);
      liststatement = 0;
    }
  }
  bufAppendC(']');
}

void shStatement(Statement p)
{
  switch(p->kind)
  {
  case is_Literal:
    bufAppendC('(');

    bufAppendS("Literal");

    bufAppendC(' ');

    shConstant(p->u.literal_.constant_);

    bufAppendC(')');

    break;
  case is_Expression:
    bufAppendC('(');

    bufAppendS("Expression");

    bufAppendC(' ');

    shExpr(p->u.expression_.expr_);

    bufAppendC(')');

    break;
  case is_SinlgeWord:
    bufAppendC('(');

    bufAppendS("SinlgeWord");

    bufAppendC(' ');

    shWord(p->u.sinlgeword_.word_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Statement!\n");
    exit(1);
  }
}

void shExpr(Expr p)
{
  switch(p->kind)
  {
  case is_Conditional:
    bufAppendC('(');

    bufAppendS("Conditional");

    bufAppendC(' ');

    shStatement(p->u.conditional_.statement_);

    bufAppendC(')');

    break;
  case is_Loop:
    bufAppendC('(');

    bufAppendS("Loop");

    bufAppendC(' ');

    shStatement(p->u.loop_.statement_);

    bufAppendC(')');

    break;
  case is_Define:
    bufAppendC('(');

    bufAppendS("Define");

    bufAppendC(' ');

    shWord(p->u.define_.word_);
  bufAppendC(' ');
    shStatement(p->u.define_.statement_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Expr!\n");
    exit(1);
  }
}

void shWord(Word p)
{
  switch(p->kind)
  {
  case is_Name:
    bufAppendC('(');

    bufAppendS("Name");

    bufAppendC(' ');

    shIdent(p->u.name_.forthword_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Word!\n");
    exit(1);
  }
}

void shConstant(Constant p)
{
  switch(p->kind)
  {
  case is_Number:
    bufAppendC('(');

    bufAppendS("Number");

    bufAppendC(' ');

    shInteger(p->u.number_.integer_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Constant!\n");
    exit(1);
  }
}

void shListExpr(ListExpr listexpr)
{
  bufAppendC('[');
  while(listexpr != 0)
  {
    if (listexpr->listexpr_)
    {
      shExpr(listexpr->expr_);
      bufAppendS(", ");
      listexpr = listexpr->listexpr_;
    }
    else
    {
      shExpr(listexpr->expr_);
      listexpr = 0;
    }
  }
  bufAppendC(']');
}

void shInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppendS(tmp);
}
void shDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppendS(tmp);
}
void shChar(Char c)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
}
void shString(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}
void shIdent(String s)
{
  bufAppendC('\"');
  bufAppendS(s);
  bufAppendC('\"');
}

void shForthWord(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}


void bufEscapeS(const char *s)
{
  if (s) while (*s) bufEscapeC(*s++);
}
void bufEscapeC(const char c)
{
  switch(c)
  {
    case '\f': bufAppendS("\\f" ); break;
    case '\n': bufAppendS("\\n" ); break;
    case '\r': bufAppendS("\\r" ); break;
    case '\t': bufAppendS("\\t" ); break;
    case '\v': bufAppendS("\\v" ); break;
    case '\\': bufAppendS("\\\\"); break;
    case '\'': bufAppendS("\\'" ); break;
    case '\"': bufAppendS("\\\""); break;
    default: bufAppendC(c);
  }
}

void bufAppendS(const char *s)
{
  size_t len = strlen(s);
  size_t n;
  while (cur_ + len >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  for(n = 0; n < len; n++)
  {
    buf_[cur_ + n] = s[n];
  }
  cur_ += len;
  buf_[cur_] = 0;
}
void bufAppendC(const char c)
{
  if (cur_ + 1 >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  buf_[cur_] = c;
  cur_++;
  buf_[cur_] = 0;
}
void bufReset(void)
{
  cur_ = 0;
  buf_size = BUFFER_INITIAL;
  resizeBuffer();
  memset(buf_, 0, buf_size);
}
void resizeBuffer(void)
{
  char *temp = (char *) malloc(buf_size);
  if (!temp)
  {
    fprintf(stderr, "Error: Out of memory while attempting to grow buffer!\n");
    exit(1);
  }
  if (buf_)
  {
    strncpy(temp, buf_, buf_size); /* peteg: strlcpy is safer, but not POSIX/ISO C. */
    free(buf_);
  }
  buf_ = temp;
}
char *buf_;
size_t cur_, buf_size;

