/* File generated by the BNF Converter (bnfc 2.9.5). */

/*** Visitor Traversal Skeleton. ***/
/* This traverses the abstract syntax tree.
   To use, copy Skeleton.h and Skeleton.c to
   new files. */

#include <stdlib.h>
#include <stdio.h>

#include "Skeleton.h"

void visitPrg(Prg p)
{
  switch(p->kind)
  {
  case is_Program:
    /* Code for Program Goes Here */
    visitListStatement(p->u.program_.liststatement_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Prg!\n");
    exit(1);
  }
}

void visitListStatement(ListStatement liststatement)
{
  while(liststatement  != 0)
  {
    /* Code For ListStatement Goes Here */
    visitStatement(liststatement->statement_);
    liststatement = liststatement->liststatement_;
  }
}

void visitStatement(Statement p)
{
  switch(p->kind)
  {
  case is_Literal:
    /* Code for Literal Goes Here */
    visitConstant(p->u.literal_.constant_);
    break;
  case is_Expression:
    /* Code for Expression Goes Here */
    visitExpr(p->u.expression_.expr_);
    break;
  case is_SinlgeWord:
    /* Code for SinlgeWord Goes Here */
    visitWord(p->u.sinlgeword_.word_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Statement!\n");
    exit(1);
  }
}

void visitExpr(Expr p)
{
  switch(p->kind)
  {
  case is_Conditional:
    /* Code for Conditional Goes Here */
    visitStatement(p->u.conditional_.statement_);
    break;
  case is_Loop:
    /* Code for Loop Goes Here */
    visitStatement(p->u.loop_.statement_);
    break;
  case is_Define:
    /* Code for Define Goes Here */
    visitWord(p->u.define_.word_);
    visitStatement(p->u.define_.statement_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Expr!\n");
    exit(1);
  }
}

void visitWord(Word p)
{
  switch(p->kind)
  {
  case is_Name:
    /* Code for Name Goes Here */
    visitForthWord(p->u.name_.forthword_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Word!\n");
    exit(1);
  }
}

void visitConstant(Constant p)
{
  switch(p->kind)
  {
  case is_Number:
    /* Code for Number Goes Here */
    visitInteger(p->u.number_.integer_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Constant!\n");
    exit(1);
  }
}

void visitListExpr(ListExpr listexpr)
{
  while(listexpr  != 0)
  {
    /* Code For ListExpr Goes Here */
    visitExpr(listexpr->expr_);
    listexpr = listexpr->listexpr_;
  }
}

void visitForthWord(ForthWord p)
{
  /* Code for ForthWord Goes Here */
}
void visitIdent(Ident i)
{
  /* Code for Ident Goes Here */
}
void visitInteger(Integer i)
{
  /* Code for Integer Goes Here */
}
void visitDouble(Double d)
{
  /* Code for Double Goes Here */
}
void visitChar(Char c)
{
  /* Code for Char Goes Here */
}
void visitString(String s)
{
  /* Code for String Goes Here */
}

