/* File generated by the BNF Converter (bnfc 2.9.5). */

#ifndef SKELETON_HEADER
#define SKELETON_HEADER
/* You might want to change the above name. */

#include "Absyn.h"


void visitPrg(Prg p);
void visitListStatement(ListStatement p);
void visitStatement(Statement p);
void visitExpr(Expr p);
void visitWord(Word p);
void visitConstant(Constant p);
void visitListExpr(ListExpr p);

void visitForthWord(ForthWord p);
void visitIdent(Ident i);
void visitInteger(Integer i);
void visitDouble(Double d);
void visitChar(Char c);
void visitString(String s);

#endif

