name: Makefile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependent commands
      run: sudo apt-get install cc65

    - name: Run build
      run: make
      
    - name: Run tests
      run: make test

    

